### ISSUE TITLE
build fails with python 3.13 / _PyObject_CallMethodIdObjArgs is removed from 3.13

### ISSUE THREAD

**Issue by smoser** [pallas/pyllhttp#5]
Python 3.13 [removed some C apis](https://docs.python.org/3/whatsnew/3.13.html#removed-c-apis) that had been deprecated since 3.9.

Below I'm building with gcc-14, which is noisier than gcc-13 due to the `-Wunused-variabler` and `-Wint-conversion` warnings.  The use of `_PyObject_CallMethodIdObjArgs` atually passes build with gcc-13 and then runtime fails like

```
# python3.13 -c 'import llhttp'
Traceback (most recent call last):
  File "<string>", line 1, in <module>
    import llhttp
  File "/pyllhttp/llhttp/__init__.py", line 1, in <module>
    from __llhttp import *
ImportError: /usr/lib/python3.13/site-packages/__llhttp.cpython-313-x86_64-linux-gnu.so: 
    undefined symbol: _PyObject_CallMethodIdObjArgs
```

The build output with gcc-14 is below.
```
$ python3.13 -m pip wheel .                                                                                                        
Processing /pyllhttp                                                        
  Installing build dependencies ... done                                                                                                                 
  Getting requirements to build wheel ... done                                                                                                           
  Preparing metadata (pyproject.toml) ... done 
Building wheels for collected packages: llhttp                                                                                                           
  Building wheel for llhttp (pyproject.toml) ... error                                                                                                   
  error: subprocess-exited-with-error                                       
                                                                                                                                                         
  × Building wheel for llhttp (pyproject.toml) did not run successfully.                                                                                 
  │ exit code: 1                                                            
  ╰─> [50 lines of output]                                                                                                                               
      running bdist_wheel                                                   
      running build                                                         
      running build_py                                                                                                                                   
      copying llhttp/__init__.py -> build/lib.linux-x86_64-cpython-313/llhttp
      running build_ext
      building '__llhttp' extension                                                                                                                      
      x86_64-pc-linux-gnu-gcc -fno-strict-overflow -Wsign-compare -DNDEBUG -g -O3 -Wall -O2 -Wall -fno-omit-frame-pointer -mno-omit-leaf-frame-pointer -m arch=x86-64-v2 -mtune=broadwell -O2 -Wall -fno-omit-frame-pointer -mno-omit-leaf-frame-pointer -march=x86-64-v2 -mtune=broadwell -fPIC -I/usr/include/python3.13 -c lib/api.c -o build/temp.linux-x86_64-cpython-313/lib/api.o
      x86_64-pc-linux-gnu-gcc -fno-strict-overflow -Wsign-compare -DNDEBUG -g -O3 -Wall -O2 -Wall -fno-omit-frame-pointer -mno-omit-leaf-frame-pointer -m arch=x86-64-v2 -mtune=broadwell -O2 -Wall -fno-omit-frame-pointer -mno-omit-leaf-frame-pointer -march=x86-64-v2 -mtune=broadwell -fPIC -I/usr/include/python3.13 -c lib/http.c -o build/temp.linux-x86_64-cpython-313/lib/http.o
      x86_64-pc-linux-gnu-gcc -fno-strict-overflow -Wsign-compare -DNDEBUG -g -O3 -Wall -O2 -Wall -fno-omit-frame-pointer -mno-omit-leaf-frame-pointer -m arch=x86-64-v2 -mtune=broadwell -O2 -Wall -fno-omit-frame-pointer -mno-omit-leaf-frame-pointer -march=x86-64-v2 -mtune=broadwell -fPIC -I/usr/include/python3.13 -c lib/llhttp.c -o build/temp.linux-x86_64-cpython-313/lib/llhttp.o
      lib/llhttp.c: In function 'llhttp__internal__run':
      lib/llhttp.c:10154:13: warning: unused variable 'avail' [-Wunused-variable]
      10154 |         int avail;
            |             ^~~~~
      lib/llhttp.c:10367:13: warning: unused variable 'avail' [-Wunused-variable]
      10367 |         int avail;
            |             ^~~~~
      lib/llhttp.c:11168:13: warning: unused variable 'avail' [-Wunused-variable]
      11168 |         int avail;
            |             ^~~~~
      x86_64-pc-linux-gnu-gcc -fno-strict-overflow -Wsign-compare -DNDEBUG -g -O3 -Wall -O2 -Wall -fno-omit-frame-pointer -mno-omit-leaf-frame-pointer -march=x86-64-v2 -mtune=broadwell -O2 -Wall -fno-omit-frame-pointer -mno-omit-leaf-frame-pointer -march=x86-64-v2 -mtune=broadwell -fPIC -I/usr/include/python3.13 -c pyllhttp.c -o build/temp.linux-x86_64-cpython-313/pyllhttp.o
      pyllhttp.c: In function 'parser_callback':
      pyllhttp.c:33:24: error: implicit declaration of function '_PyObject_CallMethodIdObjArgs'; did you mean 'PyObject_CallMethodObjArgs'? [-Wimplicit-function-declaration]
         33 |     PyObject *result = _PyObject_CallMethodIdObjArgs(llhttp->data, type, NULL);
            |                        ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~
            |                        PyObject_CallMethodObjArgs
      pyllhttp.c:33:24: error: initialization of 'PyObject *' {aka 'struct _object *'} from 'int' makes pointer from integer without a cast [-Wint-conversion]
      pyllhttp.c: In function 'parser_data_callback':
      pyllhttp.c:56:24: error: initialization of 'PyObject *' {aka 'struct _object *'} from 'int' makes pointer from integer without a cast [-Wint-conversion]
         56 |     PyObject *result = _PyObject_CallMethodIdObjArgs(llhttp->data, type, payload, NULL);
            |                        ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~
      pyllhttp.c: At top level:
      pyllhttp.c:346:1: warning: 'parser_set_lenient_keep_alive' defined but not used [-Wunused-function]
        346 | parser_set_lenient_keep_alive(PyObject *self, PyObject *value, void *closure) {
            | ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~
      pyllhttp.c:340:1: warning: 'parser_get_lenient_keep_alive' defined but not used [-Wunused-function]
        340 | parser_get_lenient_keep_alive(PyObject *self, void *closure) { 
            | ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~
      pyllhttp.c:333:1: warning: 'parser_set_lenient_chunked_length' defined but not used [-Wunused-function]
        333 | parser_set_lenient_chunked_length(PyObject *self, PyObject *value, void *closure) {
            | ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
      pyllhttp.c:327:1: warning: 'parser_get_lenient_chunked_length' defined but not used [-Wunused-function]
        327 | parser_get_lenient_chunked_length(PyObject *self, void *closure) {
            | ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
      pyllhttp.c:320:1: warning: 'parser_set_lenient_headers' defined but not used [-Wunused-function]
        320 | parser_set_lenient_headers(PyObject *self, PyObject *value, void *closure) {
            | ^~~~~~~~~~~~~~~~~~~~~~~~~~
      pyllhttp.c:314:1: warning: 'parser_get_lenient_headers' defined but not used [-Wunused-function]
        314 | parser_get_lenient_headers(PyObject *self, void *closure) {
            | ^~~~~~~~~~~~~~~~~~~~~~~~~~
      error: command '/usr/bin/x86_64-pc-linux-gnu-gcc' failed with exit code 1
      [end of output]
   
  note: This error originates from a subprocess, and is likely not a problem with pip.
  ERROR: Failed building wheel for llhttp
Failed to build llhttp
ERROR: Failed to build one or more wheels
```

**Comment by pallas** [comment]
Sorry for the delay. This is fixed.
